### ISSUE TITLE
Any plan to support 8.2?

### ISSUE THREAD

**Issue by reyrahadian** [Sitecore/experience-extractor#10]
Installed on a clean installation of 8.2 initial release but was having the following error when running with the default parameters

System.Collections.Generic.KeyNotFoundException: No parse factory registered for type ITableMapper with key "tables" (Mapper)
   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in C:\Projects\ExperienceExtractor\experience-extractor\src\ExperienceExtractor\Api\Parsing\JsonJobParser.cs:line 63
   at ExperienceExtractor.Api.Jobs.Job.<>c__DisplayClass73_0.<Run>b__0(Int32 i) in C:\Projects\ExperienceExtractor\experience-extractor\src\ExperienceExtractor\Api\Jobs\Job.cs:line 133
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ExperienceExtractor.Api.Jobs.Job.Run() in C:\Projects\ExperienceExtractor\experience-extractor\src\ExperienceExtractor\Api\Jobs\Job.cs:line 119

{
  "Id": "5b5e8afa-9716-4296-a904-fe32bb12d139",
  "Created": "2016-12-13T14:22:01.9668987+07:00",
  "Ended": "2016-12-13T14:22:02.0288855+07:00",
  "ItemsProcessed": 0,
  "RowsCreated": 0,
  "Progress": null,
  "Status": "Failed",
  "StatusText": "System.Collections.Generic.KeyNotFoundException: No parse factory registered for type ITableMapper with key \"tables\" (Mapper)\r\n   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JsonJobParser.cs:line 63\r\n   at ExperienceExtractor.Api.Jobs.Job.<>c__DisplayClass73_0.<Run>b__0(Int32 i) in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 133\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 119",
  "SizeLimitExceeded": false,
  "Url": "/sitecore/experienceextractor/jobs/5b5e8afa-9716-4296-a904-fe32bb12d139",
  "Specification": "{\r\n  \"labels\": \"en-US\",\r\n  \"source\": {\r\n    \"xdb\": {\r\n      \"filters\": [\r\n        {\r\n          \"daterange\": {\r\n            \"start\": \"2014-01-01Z\"\r\n          }\r\n        },\r\n        {\r\n          \"limit\": 1000\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"mapper\": {\r\n    \"tables\": [\r\n      {\r\n        \"name\": \"MonthlyVisits\",\r\n        \"fields\": [\r\n          {\r\n            \"date\": {\r\n              \"resolution\": \"month\"\r\n            }\r\n          },\r\n          {\r\n            \"dimension\": {\r\n              \"name\": \"Geo\",\r\n              \"fields\": [\r\n                {\r\n                  \"xa\": \"Visits/By Country\"\r\n                },\r\n                {\r\n                  \"xa\": \"Visits/By Region\"\r\n                },\r\n                {\r\n                  \"xa\": \"Visits/By City\"\r\n                }\r\n              ]\r\n            }\r\n          },\r\n          {\r\n            \"xa\": \"Visits/By Campaign\"\r\n          },\r\n          \"facts\"\r\n        ]\r\n      }\r\n    ]\r\n  },\r\n  \"postprocessors\": []\r\n}",
  "LastException": "System.Collections.Generic.KeyNotFoundException: No parse factory registered for type ITableMapper with key \"tables\" (Mapper)\r\n   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JsonJobParser.cs:line 63\r\n   at ExperienceExtractor.Api.Jobs.Job.<>c__DisplayClass73_0.<Run>b__0(Int32 i) in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 133\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 119"
}

**Comment by NielsKuhnel** [comment]
Certainly. I have just added https://github.com/Sitecore/experience-extractor/releases/download/v0.3.1/ExperienceExtractor-0.3.1-8.2.zip.

**Comment by reyrahadian** [comment]
awesome! I can see some results using your latest package.
