### ISSUE TITLE
Compatible with 8.2.1?

### ISSUE THREAD

**Issue by tpoitras** [Sitecore/experience-extractor#11]
> Compatibility
> 
> Experience Extractor has been tested with Sitecore XP 8.0 including update 1 and 2.

Does the above mean that it's compatible with 8.1.x and 8.2.x? Or does that mean 8.0.1 and 8.0.2? Because I'm researching whether or not I can implement this with Sitecore XP 8.2.1.

Thank you,

Timothy.

**Comment by NielsKuhnel** [comment]
It also works with 8.2.1. There is a separate release for it here https://github.com/Sitecore/experience-extractor/releases

Thanks for pointing this out. I have updated the readme.
