### ISSUE TITLE
Sitecore Version 8.05 Problems

### ISSUE THREAD

**Issue by berndeckmann** [Sitecore/experience-extractor#2]
After Installing on SItecore 8.05 Pressing Submit with default Values leads to errors:
System.Collections.Generic.KeyNotFoundException: No parse factory registered for type IDataSource with key "xdb" (Source) at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JsonJobParser.cs:line 70 at ExperienceExtractor.Api.Parsing.JobParser.ParseDataSource(ParseState state) in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JobParser.cs:line 58 at ExperienceExtractor.Api.Parsing.JobParser.CreateDataSource() in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JobParser.cs:line 123 at ExperienceExtractor.Api.Jobs.Job.Run() in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Jobs\Job.cs:line 105 

![image](https://cloud.githubusercontent.com/assets/4425621/10426594/e6e91356-70e1-11e5-977c-a72f7c56dc1a.png)

**Comment by berndeckmann** [comment]
On 8.01 its not working reliable. Sometimes just an empty screen. This might be due to an Javascript error firebug shows in this cases: 
TypeError: _this.app[(_this.model.get(...) + "Sampling")] is undefined...
Browser reloding a couple of times helps. Seems like a timing problem.

**Comment by NielsKuhnel** [comment]
Thanks. It turns out Experience Extractor has been built against older versions of MongoDB.Driver and MongoDB.Bson.

Until a new updated package is available, you can make it work with 8.0 update 5 by adding this to the runtime/assemblyBinding section of web.config:

    <dependentAssembly>
        <assemblyIdentity name="MongoDB.Driver" publicKeyToken="f686731cfb9cc103" xmlns="urn:schemas-microsoft-com:asm.v1" />
        <bindingRedirect oldVersion="1.0.0.0-1.10.0.62" newVersion="1.10.0.62" xmlns="urn:schemas-microsoft-com:asm.v1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="MongoDB.Bson" publicKeyToken="f686731cfb9cc103" xmlns="urn:schemas-microsoft-com:asm.v1" />
        <bindingRedirect oldVersion="1.0.0.0-1.10.0.62" newVersion="1.10.0.62" xmlns="urn:schemas-microsoft-com:asm.v1" />
      </dependentAssembly>

**Comment by NielsKuhnel** [comment]
Hi again. I have added a new download for the 0.3.0 release for update 5.

**Comment by berndeckmann** [comment]
Hi ,
where is the download?

**Comment by NielsKuhnel** [comment]
Here: https://github.com/Sitecore/experience-extractor/releases

**Comment by NielsKuhnel** [comment]
The new package works with update 5.
