### ISSUE TITLE
Parse Factory Exception

### ISSUE THREAD

**Issue by dsolovay** [Sitecore/experience-extractor#3]
Attempted to install with SItecore 8.1 Initial Release.  After clicking submit, I get this exception:

````
System.Collections.Generic.KeyNotFoundException: No parse factory registered for type IDataSource with key "xdb" (Source)
   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JsonJobParser.cs:line 70
   at ExperienceExtractor.Api.Parsing.JobParser.ParseDataSource(ParseState state) in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JobParser.cs:line 58
   at ExperienceExtractor.Api.Parsing.JobParser.CreateDataSource() in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JobParser.cs:line 123
   at ExperienceExtractor.Api.Jobs.Job.Run() in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Jobs\Job.cs:line 105

{
  "Id": "7e3a21be-a384-4ec1-b18d-51f25317e0c2",
  "Created": "2015-10-28T13:59:38.4851717-04:00",
  "Ended": "2015-10-28T13:59:38.4891719-04:00",
  "ItemsProcessed": 0,
  "Progress": null,
  "Status": "Failed",
  "StatusText": "System.Collections.Generic.KeyNotFoundException: No parse factory registered for type IDataSource with key \"xdb\" (Source)\r\n   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JsonJobParser.cs:line 70\r\n   at ExperienceExtractor.Api.Parsing.JobParser.ParseDataSource(ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 58\r\n   at ExperienceExtractor.Api.Parsing.JobParser.CreateDataSource() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 123\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 105",
  "SizeLimitExceeded": false,
  "Url": "/sitecore/experienceextractor/jobs/7e3a21be-a384-4ec1-b18d-51f25317e0c2",
  "Specification": "{\r\n  \"source\": {\r\n    \"xdb\": {\r\n      \"filters\": [\r\n        {\r\n          \"sample\": 0.3\r\n        },\r\n        {\r\n          \"daterange\": {\r\n            \"start\": \"2015-10-24Z\",\r\n            \"end\": \"2015-10-29Z\"\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"mapper\": {\r\n    \"tables\": [\r\n      {\r\n        \"name\": \"Visits\",\r\n        \"fields\": [\r\n          {\r\n            \"date\": \"Date\"\r\n          },\r\n          \"facts\"\r\n        ],\r\n        \"tables\": []\r\n      }\r\n    ]\r\n  },\r\n  \"postprocessors\": [\r\n    \"msaccess\"\r\n  ]\r\n}",
  "LastException": "System.Collections.Generic.KeyNotFoundException: No parse factory registered for type IDataSource with key \"xdb\" (Source)\r\n   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JsonJobParser.cs:line 70\r\n   at ExperienceExtractor.Api.Parsing.JobParser.ParseDataSource(ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 58\r\n   at ExperienceExtractor.Api.Parsing.JobParser.CreateDataSource() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 123\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 105"
}
````

**Comment by NielsKuhnel** [comment]
Yes, MongoDB dependencies were updated in 8.0 update 5, and this is also the case for 8.1.
Try downloading the package for update 5 [here](https://github.com/Sitecore/experience-extractor/releases), and see if it doesn't work. I haven't validated it fully with 8.1, but I have seen data come through with this build on 8.1.

**Comment by kalotra** [comment]
Hello. I installed ExperienceExtractor-0.3.0-update5.zip on Sitecore 8.1 and got following error.

System.Collections.Generic.KeyNotFoundException: No parse factory registered for type IDataSource with key "xdb" (Source)
   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JsonJobParser.cs:line 67
   at ExperienceExtractor.Api.Parsing.JobParser.ParseDataSource(ParseState state) in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JobParser.cs:line 69
   at ExperienceExtractor.Api.Parsing.JobParser.CreateDataSource() in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JobParser.cs:line 134
   at ExperienceExtractor.Api.Jobs.Job.Run() in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Jobs\Job.cs:line 109

{
  "Id": "ec2f9949-9d8f-4b81-9095-fc6457b314eb",
  "Created": "2015-12-03T11:24:21.5694406-05:00",
  "Ended": "2015-12-03T11:24:21.5850626-05:00",
  "ItemsProcessed": 0,
  "RowsCreated": 0,
  "Progress": null,
  "Status": "Failed",
  "StatusText": "System.Collections.Generic.KeyNotFoundException: No parse factory registered for type IDataSource with key \"xdb\" (Source)\r\n   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JsonJobParser.cs:line 67\r\n   at ExperienceExtractor.Api.Parsing.JobParser.ParseDataSource(ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 69\r\n   at ExperienceExtractor.Api.Parsing.JobParser.CreateDataSource() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 134\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 109",
  "SizeLimitExceeded": false,
  "Url": "/sitecore/experienceextractor/jobs/ec2f9949-9d8f-4b81-9095-fc6457b314eb",
  "Specification": "{\r\n  \"source\": {\r\n    \"xdb\": {\r\n      \"filters\": [\r\n        {\r\n          \"sample\": 0.3\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"mapper\": {\r\n    \"tables\": [\r\n      {\r\n        \"name\": \"Visits\",\r\n        \"fields\": [\r\n          {\r\n            \"date\": \"Date\"\r\n          },\r\n          {\r\n            \"xa\": \"Visits/By goal\"\r\n          },\r\n          \"facts\"\r\n        ],\r\n        \"tables\": []\r\n      }\r\n    ]\r\n  },\r\n  \"postprocessors\": [\r\n    \"msaccess\"\r\n  ]\r\n}",
  "LastException": "System.Collections.Generic.KeyNotFoundException: No parse factory registered for type IDataSource with key \"xdb\" (Source)\r\n   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JsonJobParser.cs:line 67\r\n   at ExperienceExtractor.Api.Parsing.JobParser.ParseDataSource(ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 69\r\n   at ExperienceExtractor.Api.Parsing.JobParser.CreateDataSource() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 134\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 109"
}

**Comment by NielsKuhnel** [comment]
I can't reproduce on my 8.1 install. Do you have any assembly load exceptions in your log files?

**Comment by dsolovay** [comment]
Your proposed workaround worked for me.

**Comment by SamridhiSachdeva** [comment]
Hello. 
I installed ExperienceExtractor-0.3.0 on Sitecore 8.2 and got following error.

System.Collections.Generic.KeyNotFoundException: No parse factory registered for type IDataSource with key "xdb" (Source)
   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JsonJobParser.cs:line 67
   at ExperienceExtractor.Api.Parsing.JobParser.ParseDataSource(ParseState state) in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JobParser.cs:line 69
   at ExperienceExtractor.Api.Parsing.JobParser.CreateDataSource() in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Parsing\JobParser.cs:line 134
   at ExperienceExtractor.Api.Jobs.Job.Run() in c:\Projects\ExperienceExtractor\Git\experience-extractor\src\ExperienceExtractor\Api\Jobs\Job.cs:line 109

{
  "Id": "8c15d967-7ff8-4e00-b8f6-e9f37148385f",
  "Created": "2017-02-01T11:41:44.1180603+05:30",
  "Ended": "2017-02-01T11:41:44.1220583+05:30",
  "ItemsProcessed": 0,
  "RowsCreated": 0,
  "Progress": null,
  "Status": "Failed",
  "StatusText": "System.Collections.Generic.KeyNotFoundException: No parse factory registered for type IDataSource with key \"xdb\" (Source)\r\n   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JsonJobParser.cs:line 67\r\n   at ExperienceExtractor.Api.Parsing.JobParser.ParseDataSource(ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 69\r\n   at ExperienceExtractor.Api.Parsing.JobParser.CreateDataSource() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 134\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 109",
  "SizeLimitExceeded": false,
  "Url": "/sitecore/experienceextractor/jobs/8c15d967-7ff8-4e00-b8f6-e9f37148385f",
  "Specification": "{\r\n  \"labels\": \"en-US\",\r\n  \"source\": {\r\n    \"xdb\": {\r\n      \"filters\": [\r\n        {\r\n          \"daterange\": {\r\n            \"start\": \"2014-01-01Z\"\r\n          }\r\n        },\r\n        {\r\n          \"limit\": 1000\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"mapper\": {\r\n    \"tables\": [\r\n      {\r\n        \"name\": \"MonthlyVisits\",\r\n        \"fields\": [\r\n          {\r\n            \"date\": {\r\n              \"resolution\": \"month\"\r\n            }\r\n          },\r\n          {\r\n            \"dimension\": {\r\n              \"name\": \"Geo\",\r\n              \"fields\": [\r\n                {\r\n                  \"xa\": \"Visits/By Country\"\r\n                },\r\n                {\r\n                  \"xa\": \"Visits/By Region\"\r\n                },\r\n                {\r\n                  \"xa\": \"Visits/By City\"\r\n                }\r\n              ]\r\n            }\r\n          },\r\n          {\r\n            \"xa\": \"Visits/By Campaign\"\r\n          },\r\n          \"facts\"\r\n        ]\r\n      }\r\n    ]\r\n  },\r\n  \"postprocessors\": []\r\n}",
  "LastException": "System.Collections.Generic.KeyNotFoundException: No parse factory registered for type IDataSource with key \"xdb\" (Source)\r\n   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JsonJobParser.cs:line 67\r\n   at ExperienceExtractor.Api.Parsing.JobParser.ParseDataSource(ParseState state) in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 69\r\n   at ExperienceExtractor.Api.Parsing.JobParser.CreateDataSource() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JobParser.cs:line 134\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in c:\\Projects\\ExperienceExtractor\\Git\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 109"
}

**Comment by Kalaiyarasanak** [comment]
Hi,

We are using sitecore 8.2.5 in our project and i recently came across Experience Extractor. When i tried to install the latest version 0.3.1-8.2, i am not getting any dimensions from the drop down. and so when i try to extract the empty values, i get the below error:

![image](https://user-images.githubusercontent.com/36231731/35931586-03959e68-0c5b-11e8-93e8-e864beea33f9.png)

This can possible because, the extractor unable to grab the values from XDB. 
@NielsKuhnel : will you be able to help me here?

Thanks in advance,
Kalai.

**Comment by nielskuhnel** [comment]
Hi, this is most likely caused by assembly load issues because of incompatible dependency versions (mongo driver etc). If this is the case you should be able to find exceptions related to asembly loading in the general Sitecore error log. I have limited time for this at the moment, and my best suggestion is that you try to build from source yourself using your specific Sitecore assemblies. Let me know if this works.
